import { AppstoreOutlined, DownloadOutlined, EditOutlined, EnvironmentOutlined, EyeOutlined, MoreOutlined, PlusOutlined, SearchOutlined } from '@ant-design/icons'
import { App, Button, Card, Col, Dropdown, Input, Pagination, Row, Select, Segmented, Space, Table, Tag, Typography } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useMemo, useState } from 'react'
import { PageHeader } from '@/components/layout/PageHeader'
import { formatDate } from '@/lib/format'
import { PROJECT_STATUS, apiErrorMessage, labelOf, useProjectMutations, useProjects, type Project, type ProjectStatus } from '../api'
import { ProjectFormModal } from '../components/ProjectFormModal'
import { ProjectDetailModal } from '../components/ProjectDetailModal'

const tone: Record<ProjectStatus, string> = { PLANNING: 'gold', SELLING: 'green', SOLD_OUT: 'blue', CLOSED: 'default' }
/** 9.14: card mặc định Stitch, bảng là view phụ; server pagination + keyword/status/investor thật. */
export function ProjectsPage() {
  const { message, modal } = App.useApp(); const [view, setView] = useState<'card' | 'table'>('card'); const [keyword, setKeyword] = useState(''); const [status, setStatus] = useState<ProjectStatus | undefined>(); const [investor, setInvestor] = useState<string | undefined>(); const [page, setPage] = useState(0); const [size, setSize] = useState(6); const [form, setForm] = useState<Project | null | undefined>(undefined); const [detailProjectId, setDetailProjectId] = useState<string>()
  const list = useProjects({ keyword: keyword || undefined, status, investor: investor || undefined, page, size, sort: 'createdAt,desc' }); const mutations = useProjectMutations()
  const investors = useMemo(() => [...new Set((list.data?.content ?? []).map((p) => p.investor).filter((v): v is string => Boolean(v)))], [list.data])
  const remove = (p: Project) => modal.confirm({ title: `Xoá dự án ${p.name}?`, content: 'Chỉ xoá được dự án chưa có sản phẩm.', okText: 'Xoá', cancelText: 'Huỷ', okButtonProps: { danger: true }, onOk: () => mutations.remove.mutateAsync(p.id).then(() => message.success('Đã xoá dự án')).catch((e) => { message.error(apiErrorMessage(e)); throw e }) })
  const openEdit = (project: Project) => { setDetailProjectId(undefined); setForm(project) }
  const columns: ColumnsType<Project> = [
    { title: 'Dự án', dataIndex: 'name', render: (v, p) => <button type="button" className="project-table__name" onClick={() => setDetailProjectId(p.id)}>{v}</button> }, { title: 'Địa điểm', dataIndex: 'location', render: (v) => v || '—' }, { title: 'Chủ đầu tư', dataIndex: 'investor', render: (v) => v || '—' }, { title: 'Trạng thái', dataIndex: 'status', render: (v: ProjectStatus) => <Tag color={tone[v]}>{labelOf(PROJECT_STATUS, v)}</Tag> }, { title: 'Cập nhật', dataIndex: 'updatedAt', render: formatDate }, { title: '', width: 54, render: (_, p) => <Dropdown menu={{ items: [{ key: 'view', label: 'Xem chi tiết', icon: <EyeOutlined /> }, { key: 'edit', label: 'Chỉnh sửa', icon: <EditOutlined /> }, { key: 'delete', label: 'Xoá', danger: true }], onClick: ({ key }) => key === 'view' ? setDetailProjectId(p.id) : key === 'edit' ? openEdit(p) : remove(p) }}><Button type="text" icon={<MoreOutlined />} /></Dropdown> },
  ]
  return <><PageHeader breadcrumb={[{ title: 'Danh mục' }, { title: 'Dự án' }]} title="Danh sách dự án" meta="Quản lý toàn bộ dự án bất động sản và theo dõi tình trạng triển khai." actions={<><Segmented value={view} onChange={(v) => setView(v as typeof view)} options={[{ label: 'Lưới card', value: 'card' }, { label: 'Bảng', value: 'table' }]} /><Button icon={<DownloadOutlined />} onClick={() => message.info('Xuất báo cáo cần API báo cáo dự án')}>Xuất dữ liệu</Button><Button type="primary" icon={<PlusOutlined />} onClick={() => setForm(null)}>Thêm dự án</Button></>} />
    <Card className="stitch-card" variant="borderless" styles={{ body: { padding: 16 } }}><Row gutter={[12, 12]}><Col xs={24} md={10}><Input size="large" prefix={<SearchOutlined />} placeholder="Tìm theo tên dự án, địa điểm, chủ đầu tư..." value={keyword} onChange={(e) => { setKeyword(e.target.value); setPage(0) }} /></Col><Col xs={12} md={5}><Select allowClear size="large" style={{ width: '100%' }} placeholder="Tất cả trạng thái" value={status} onChange={(v) => { setStatus(v); setPage(0) }} options={PROJECT_STATUS} /></Col><Col xs={12} md={5}><Select allowClear size="large" style={{ width: '100%' }} placeholder="Tất cả chủ đầu tư" value={investor} onChange={(v) => { setInvestor(v); setPage(0) }} options={investors.map((value) => ({ value, label: value }))} /></Col><Col xs={24} md={4}><Button size="large" block onClick={() => { setKeyword(''); setStatus(undefined); setInvestor(undefined); setPage(0) }}>Xoá lọc</Button></Col></Row></Card>
    {view === 'table' ? <Card className="stitch-card" variant="borderless" style={{ marginTop: 16 }}><Table rowKey="id" loading={list.isLoading} columns={columns} dataSource={list.data?.content} scroll={{ x: 'max-content' }} pagination={false} locale={{ emptyText: list.isError ? apiErrorMessage(list.error) : 'Chưa có dự án phù hợp' }} /></Card> : <Row gutter={[16, 16]} style={{ marginTop: 16 }}>{(list.data?.content ?? []).map((p) => <Col key={p.id} xs={24} md={12} xl={8}><Card className="stitch-card project-card project-card--clickable" variant="borderless" tabIndex={0} role="button" aria-label={`Xem dự án ${p.name}`} onClick={() => setDetailProjectId(p.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setDetailProjectId(p.id) } }} cover={<div className="project-card__cover">{p.imageUrl && <img src={p.imageUrl} alt="" onError={(event) => { event.currentTarget.style.display = 'none' }} />}<AppstoreOutlined /><Tag color={tone[p.status]}>{labelOf(PROJECT_STATUS, p.status)}</Tag></div>}><Typography.Text type="secondary" className="project-code">DỰ ÁN</Typography.Text><Typography.Title level={4} ellipsis={{ rows: 2 }} style={{ margin: '4px 0 10px' }}>{p.name}</Typography.Title><Space direction="vertical" size={5} style={{ width: '100%' }}><Typography.Text type="secondary"><EnvironmentOutlined /> {p.location || 'Chưa cập nhật địa điểm'}</Typography.Text><Typography.Text type="secondary">Chủ đầu tư: {p.investor || 'Chưa cập nhật'}</Typography.Text><Typography.Text type="secondary">Tạo ngày {formatDate(p.createdAt)}</Typography.Text></Space></Card></Col>)}</Row>}
    <div className="project-pagination"><Pagination current={page + 1} pageSize={size} total={list.data?.totalElements ?? 0} showSizeChanger pageSizeOptions={[6, 12, 24]} onChange={(p, s) => { setPage(p - 1); setSize(s) }} showTotal={(total, range) => `Hiển thị ${range[0]} - ${range[1]} trên tổng số ${total} dự án`} /></div>
    <ProjectFormModal open={form !== undefined} editing={form ?? null} submitting={mutations.create.isPending || mutations.update.isPending || mutations.uploadProjectImage.isPending} onCancel={() => setForm(undefined)} onSubmit={(body, image) => { void (async () => { try { const saved = form ? await mutations.update.mutateAsync({ id: form.id, body }) : await mutations.create.mutateAsync(body); if (image) await mutations.uploadProjectImage.mutateAsync({ id: saved.id, file: image }); message.success(form ? 'Đã cập nhật dự án' : 'Đã tạo dự án'); setForm(undefined) } catch (e) { message.error(apiErrorMessage(e)) } })() }} />
    <ProjectDetailModal projectId={detailProjectId} onClose={() => setDetailProjectId(undefined)} onEdit={openEdit} />
  </>
}