import { DeleteOutlined, EditOutlined, SearchOutlined } from '@ant-design/icons'
import { Button, Card, Col, Dropdown, Input, InputNumber, Pagination, Row, Select, Table, Tag } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { formatMoney } from '@/lib/format'
import { DIRECTION, PRODUCT_STATUS, PRODUCT_TYPE, apiErrorMessage, labelOf, type Product, type ProductFilters, type ProductStatus, type ProductType } from '../api'

interface Props { data: { content: Product[]; totalElements: number } | undefined; error: unknown; loading: boolean; filters: ProductFilters; onFiltersChange: (filters: ProductFilters) => void; onEdit: (product: Product) => void; onDelete: (product: Product) => void; onPreview: (src: string) => void }
const tone: Record<ProductStatus, string> = { AVAILABLE: 'green', RESERVED: 'gold', SOLD: 'default' }

/** Bảng product server-side: chỉ filter API hiện hỗ trợ, không thêm bulk action giả. */
export function ProjectProductsTable({ data, error, loading, filters, onFiltersChange, onEdit, onDelete, onPreview }: Props) {
  const patch = <K extends keyof ProductFilters>(key: K, value: ProductFilters[K]) => onFiltersChange({ ...filters, [key]: value, page: 0 })
  const columns: ColumnsType<Product> = [
    { title: 'Mã sản phẩm', dataIndex: 'code', width: 145, render: (value) => <span className="project-product-code">{value}</span> }, { title: 'Block / phân khu', dataIndex: 'block', width: 150, render: (value) => value || '—' }, { title: 'Loại hình', dataIndex: 'type', width: 132, render: (value: ProductType) => labelOf(PRODUCT_TYPE, value) }, { title: 'Diện tích', dataIndex: 'area', width: 112, render: (value) => `${value} m²` }, { title: 'Hướng', dataIndex: 'direction', width: 110, render: (value) => labelOf(DIRECTION, value) }, { title: 'Giá niêm yết', dataIndex: 'price', width: 175, align: 'right', render: formatMoney }, { title: 'Trạng thái', dataIndex: 'status', width: 142, render: (value: ProductStatus) => <Tag color={tone[value]}>{labelOf(PRODUCT_STATUS, value)}</Tag> }, { title: '', width: 60, fixed: 'right', render: (_, item) => <Dropdown menu={{ items: [{ key: 'edit', label: 'Chỉnh sửa', icon: <EditOutlined /> }, { key: 'delete', label: 'Xóa', danger: true, icon: <DeleteOutlined /> }], onClick: ({ key }) => key === 'edit' ? onEdit(item) : onDelete(item) }}><Button type="text" icon={<EditOutlined />} aria-label={`Thao tác với ${item.code}`} /></Dropdown> },
  ]
  /** Chỉ thêm cột ảnh khi trang hiện tại thật sự có ảnh, tránh cột trống cho 26 dự án chưa có ảnh. */
  if ((data?.content ?? []).some((product) => product.imageUrl)) columns.unshift({ title: 'Ảnh', dataIndex: 'imageUrl', width: 64, render: (value: string) => value ? <button type="button" className="project-product-thumb" onClick={() => onPreview(value)} aria-label="Xem ảnh sản phẩm"><img src={value} alt="" /></button> : '—' })
  return <section className="project-products"><Card className="stitch-card project-products__filters" variant="borderless"><Row gutter={[12, 12]}><Col xs={24} lg={5}><Input size="large" prefix={<SearchOutlined />} placeholder="Tìm theo mã sản phẩm..." value={filters.keyword} onChange={(event) => patch('keyword', event.target.value || undefined)} /></Col><Col xs={12} sm={8} lg={3}><Input size="large" placeholder="Block / khu" value={filters.block} onChange={(event) => patch('block', event.target.value || undefined)} /></Col><Col xs={12} sm={8} lg={4}><Select allowClear size="large" placeholder="Loại sản phẩm" value={filters.type} onChange={(value) => patch('type', value)} style={{ width: '100%' }} options={PRODUCT_TYPE} /></Col><Col xs={12} sm={8} lg={4}><Select allowClear size="large" placeholder="Trạng thái" value={filters.status} onChange={(value) => patch('status', value)} style={{ width: '100%' }} options={PRODUCT_STATUS} /></Col><Col xs={12} sm={8} lg={3}><InputNumber min={0} size="large" placeholder="Giá từ" value={filters.minPrice} onChange={(value) => patch('minPrice', value ?? undefined)} style={{ width: '100%' }} /></Col><Col xs={12} sm={8} lg={3}><InputNumber min={0} size="large" placeholder="Giá đến" value={filters.maxPrice} onChange={(value) => patch('maxPrice', value ?? undefined)} style={{ width: '100%' }} /></Col><Col xs={12} sm={8} lg={2}><Button size="large" block onClick={() => onFiltersChange({ page: 0, size: filters.size })}>Xóa lọc</Button></Col></Row></Card><Card className="stitch-card project-products__table" variant="borderless" styles={{ body: { padding: 0 } }}><Table rowKey="id" loading={loading} columns={columns} dataSource={data?.content} pagination={false} scroll={{ x: 1000 }} locale={{ emptyText: error ? apiErrorMessage(error) : 'Chưa có sản phẩm phù hợp' }} /></Card><div className="project-products__pagination"><Pagination current={(filters.page ?? 0) + 1} pageSize={filters.size ?? 10} total={data?.totalElements ?? 0} showSizeChanger pageSizeOptions={[10, 20, 50]} onChange={(page, size) => onFiltersChange({ ...filters, page: page - 1, size })} showTotal={(total, range) => `Hiển thị ${range[0]}–${range[1]} / ${total} sản phẩm`} /></div></section>
}